// MFCApplication2.idl : type library source for MFCApplication2.exe

// This file will be processed by the MIDL compiler to produce the
// type library (MFCApplication2.tlb).

[ uuid(B6D508C4-3372-4200-9BD0-7D802CEA3762), version(1.0) ]
library MFCApplication2
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  Primary dispatch interface for CMFCApplication2Doc
	
	[ uuid(04C4B1CF-A11B-44B3-912D-CD6E3C3CD139) ]
	dispinterface IMFCApplication2
	{
		properties:
			
		methods:
	};

	//  Class information for CMFCApplication2Doc
	
	[ uuid(3DE44035-086A-4983-9CC8-FA829C918770) ]
	coclass MFCApplication2
	{
		[default] dispinterface IMFCApplication2;
	};
};
